### ISSUE TITLE
/run/shm/sciond/default.sock is gone

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-deploy#46]
Sometimes we find errors, in particular in the attachment points, where `bwtestserver` is not working correctly. Listing `/run/shm/` shows no `sciond` directory there.
We believe it might be related to systemd removal of IPC: https://superuser.com/a/1179962/541170

We are running a `auditd` in all four APs, started like:
`sudo auditctl -w /run/shm/sciond/  -p wa -k sciondsocketdelete`
You can consult the auditd entries like:
`sudo ausearch -i -k sciondsocketdelete | grep DELETE`

**Comment by matzf** [comment]
Repository archived, closed.
